### PR TITLE
Implementation of Ecosia option

### PR DESCRIPTION
**Pull request by andrasdenes**
Implemented Ecosia search, so people can do good while using this library.
Added parameter: "eco"
"eco" defaults to False (not forcing anyone to use)

Updated README.md accordingly

### CODE REVIEW

**Comment by serhii73** [comment]
Thank you very much for your PR.
Can you resolve git conflict?
Thank you very much!

**Comment by andrasdenes** [comment]
Resolved

**Comment by serhii73** [comment]
Sorry. The last merge request created a new git conflict.
Can you resolve and I will merge it?

**Comment by andrasdenes** [comment]
re-implemented based on previous. Tested.

**Pull request merged**
