### PR TITLE
Now will return list of 5 results by using get_list

### PR DESCRIPTION
**Pull request by NicholasG04**

### CODE REVIEW

**Comment by NicholasG04** [comment]
satisfies #2

**Comment by NicholasG04** [comment]
Please note that my code is in addition to the one website one and will return the top five results neatly into the application. It can also be very easily modified to simply return the array just by returning 'website_list'!

**Comment by serhii73** [comment]
Can you please resolve the Git conflict?
Thank you very much!

**Comment by NicholasG04** [comment]
I mean really it's reliant on you deciding what you want. Do you want my implementation where you have the option for both or just an implementation which solely returns a list. You have to decide

**Comment by serhii73** [comment]
Yes, you're right.
I think I close this PR.
Thank you very much!

**Pull request closed without merging**
