### PR TITLE
Improved README.md

### PR DESCRIPTION
**Pull request by NicholasG04**
Issue #4

### CODE REVIEW

**Comment by serhii73** [comment]
Thank you very much for your PR.
But I do not use API.
https://github.com/serhii73/find_the_site/blob/master/find_the_site/fw.py

**Comment by NicholasG04** [comment]
This is indeed true, let me reword that slightly!

**Comment by NicholasG04** [comment]
Also added information about the other command I added, `get_list` from PR #10

**Comment by serhii73** [comment]
Can you fix the git conflict?

**Comment by NicholasG04** [comment]
Done!

**Comment by serhii73** [comment]
Can you please resolve the Git conflict?
Thank you very much!

**Pull request closed without merging**
